# Created a pre-built image for this project on:
# https://hub.docker.com/repository/docker/evandrocoan/ubuntu18nodejsjavagithub
#
# docker build . -f Dockerfile-all -t evandrocoan/ubuntu18nodejsjavagithub
# docker run -it evandrocoan/ubuntu18nodejsjavagithub
# # nodejs --version
# # exit
# docker login docker.io
# docker push evandrocoan/ubuntu18nodejsjavagithub

FROM ubuntu:18.04

# https://docs.docker.com/engine/reference/builder/
EXPOSE 3000
EXPOSE 8081

COPY . /app
WORKDIR /app

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME \
    && set -x \
    && apt-get update \
    && apt-get install -y iputils-ping dnsutils iproute2 openjdk-8-jdk maven curl apt-utils ca-certificates-java \
    && update-ca-certificates -f \
    && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/* \
    && cd reactfrontend \
    && npm install \
    && cd .. \
    && cd javabackend \
    && mvn package

CMD ip a s && bash run_servers.sh
